server:
  port: 8088

spring:
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resodl_apartment?useOldAliasMetadataBehavior=true&serverTimezone=UTC
  jackson:
    date-format: yyyy-MM-dd # 返回json时自动格式化日期
  resources:
    static-locations: classpath:/META- INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,classpath:/templates/static,classpath:/templates/Document,classpath:/mapper ,classpath:/resources/JS# 静态资源访问路径
  thymeleaf:
    suffix: .html
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/denglus/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl